name = "hackernews-dark-reader"
type = "javascript"
route = ''
account_id = 'bc303f69f8308acc5e9a283658a7727d'
zone_id = '7b8bb6377a5f8dfc79ea13fb23c04420'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "./workers-site"}
compatibility_date = "2022-01-27"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"